# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /tmp/liboat-git

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /tmp/liboat-git

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /tmp/liboat-git/CMakeFiles /tmp/liboat-git/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /tmp/liboat-git/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Gramk

# Build rule for target.
Gramk: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Gramk
.PHONY : Gramk

# fast build rule for target.
Gramk/fast:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/build
.PHONY : Gramk/fast

core/oat.o: core/oat.cpp.o

.PHONY : core/oat.o

# target to build an object file
core/oat.cpp.o:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat.cpp.o
.PHONY : core/oat.cpp.o

core/oat.i: core/oat.cpp.i

.PHONY : core/oat.i

# target to preprocess a source file
core/oat.cpp.i:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat.cpp.i
.PHONY : core/oat.cpp.i

core/oat.s: core/oat.cpp.s

.PHONY : core/oat.s

# target to generate assembly for a file
core/oat.cpp.s:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat.cpp.s
.PHONY : core/oat.cpp.s

core/oat_box.o: core/oat_box.cpp.o

.PHONY : core/oat_box.o

# target to build an object file
core/oat_box.cpp.o:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_box.cpp.o
.PHONY : core/oat_box.cpp.o

core/oat_box.i: core/oat_box.cpp.i

.PHONY : core/oat_box.i

# target to preprocess a source file
core/oat_box.cpp.i:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_box.cpp.i
.PHONY : core/oat_box.cpp.i

core/oat_box.s: core/oat_box.cpp.s

.PHONY : core/oat_box.s

# target to generate assembly for a file
core/oat_box.cpp.s:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_box.cpp.s
.PHONY : core/oat_box.cpp.s

core/oat_button.o: core/oat_button.cpp.o

.PHONY : core/oat_button.o

# target to build an object file
core/oat_button.cpp.o:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_button.cpp.o
.PHONY : core/oat_button.cpp.o

core/oat_button.i: core/oat_button.cpp.i

.PHONY : core/oat_button.i

# target to preprocess a source file
core/oat_button.cpp.i:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_button.cpp.i
.PHONY : core/oat_button.cpp.i

core/oat_button.s: core/oat_button.cpp.s

.PHONY : core/oat_button.s

# target to generate assembly for a file
core/oat_button.cpp.s:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_button.cpp.s
.PHONY : core/oat_button.cpp.s

core/oat_buttonmodule.o: core/oat_buttonmodule.cpp.o

.PHONY : core/oat_buttonmodule.o

# target to build an object file
core/oat_buttonmodule.cpp.o:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_buttonmodule.cpp.o
.PHONY : core/oat_buttonmodule.cpp.o

core/oat_buttonmodule.i: core/oat_buttonmodule.cpp.i

.PHONY : core/oat_buttonmodule.i

# target to preprocess a source file
core/oat_buttonmodule.cpp.i:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_buttonmodule.cpp.i
.PHONY : core/oat_buttonmodule.cpp.i

core/oat_buttonmodule.s: core/oat_buttonmodule.cpp.s

.PHONY : core/oat_buttonmodule.s

# target to generate assembly for a file
core/oat_buttonmodule.cpp.s:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_buttonmodule.cpp.s
.PHONY : core/oat_buttonmodule.cpp.s

core/oat_checkform.o: core/oat_checkform.cpp.o

.PHONY : core/oat_checkform.o

# target to build an object file
core/oat_checkform.cpp.o:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_checkform.cpp.o
.PHONY : core/oat_checkform.cpp.o

core/oat_checkform.i: core/oat_checkform.cpp.i

.PHONY : core/oat_checkform.i

# target to preprocess a source file
core/oat_checkform.cpp.i:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_checkform.cpp.i
.PHONY : core/oat_checkform.cpp.i

core/oat_checkform.s: core/oat_checkform.cpp.s

.PHONY : core/oat_checkform.s

# target to generate assembly for a file
core/oat_checkform.cpp.s:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_checkform.cpp.s
.PHONY : core/oat_checkform.cpp.s

core/oat_color.o: core/oat_color.cpp.o

.PHONY : core/oat_color.o

# target to build an object file
core/oat_color.cpp.o:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_color.cpp.o
.PHONY : core/oat_color.cpp.o

core/oat_color.i: core/oat_color.cpp.i

.PHONY : core/oat_color.i

# target to preprocess a source file
core/oat_color.cpp.i:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_color.cpp.i
.PHONY : core/oat_color.cpp.i

core/oat_color.s: core/oat_color.cpp.s

.PHONY : core/oat_color.s

# target to generate assembly for a file
core/oat_color.cpp.s:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_color.cpp.s
.PHONY : core/oat_color.cpp.s

core/oat_container.o: core/oat_container.cpp.o

.PHONY : core/oat_container.o

# target to build an object file
core/oat_container.cpp.o:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_container.cpp.o
.PHONY : core/oat_container.cpp.o

core/oat_container.i: core/oat_container.cpp.i

.PHONY : core/oat_container.i

# target to preprocess a source file
core/oat_container.cpp.i:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_container.cpp.i
.PHONY : core/oat_container.cpp.i

core/oat_container.s: core/oat_container.cpp.s

.PHONY : core/oat_container.s

# target to generate assembly for a file
core/oat_container.cpp.s:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_container.cpp.s
.PHONY : core/oat_container.cpp.s

core/oat_cross.o: core/oat_cross.cpp.o

.PHONY : core/oat_cross.o

# target to build an object file
core/oat_cross.cpp.o:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_cross.cpp.o
.PHONY : core/oat_cross.cpp.o

core/oat_cross.i: core/oat_cross.cpp.i

.PHONY : core/oat_cross.i

# target to preprocess a source file
core/oat_cross.cpp.i:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_cross.cpp.i
.PHONY : core/oat_cross.cpp.i

core/oat_cross.s: core/oat_cross.cpp.s

.PHONY : core/oat_cross.s

# target to generate assembly for a file
core/oat_cross.cpp.s:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_cross.cpp.s
.PHONY : core/oat_cross.cpp.s

core/oat_dial.o: core/oat_dial.cpp.o

.PHONY : core/oat_dial.o

# target to build an object file
core/oat_dial.cpp.o:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_dial.cpp.o
.PHONY : core/oat_dial.cpp.o

core/oat_dial.i: core/oat_dial.cpp.i

.PHONY : core/oat_dial.i

# target to preprocess a source file
core/oat_dial.cpp.i:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_dial.cpp.i
.PHONY : core/oat_dial.cpp.i

core/oat_dial.s: core/oat_dial.cpp.s

.PHONY : core/oat_dial.s

# target to generate assembly for a file
core/oat_dial.cpp.s:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_dial.cpp.s
.PHONY : core/oat_dial.cpp.s

core/oat_font.o: core/oat_font.cpp.o

.PHONY : core/oat_font.o

# target to build an object file
core/oat_font.cpp.o:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_font.cpp.o
.PHONY : core/oat_font.cpp.o

core/oat_font.i: core/oat_font.cpp.i

.PHONY : core/oat_font.i

# target to preprocess a source file
core/oat_font.cpp.i:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_font.cpp.i
.PHONY : core/oat_font.cpp.i

core/oat_font.s: core/oat_font.cpp.s

.PHONY : core/oat_font.s

# target to generate assembly for a file
core/oat_font.cpp.s:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_font.cpp.s
.PHONY : core/oat_font.cpp.s

core/oat_icon.o: core/oat_icon.cpp.o

.PHONY : core/oat_icon.o

# target to build an object file
core/oat_icon.cpp.o:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_icon.cpp.o
.PHONY : core/oat_icon.cpp.o

core/oat_icon.i: core/oat_icon.cpp.i

.PHONY : core/oat_icon.i

# target to preprocess a source file
core/oat_icon.cpp.i:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_icon.cpp.i
.PHONY : core/oat_icon.cpp.i

core/oat_icon.s: core/oat_icon.cpp.s

.PHONY : core/oat_icon.s

# target to generate assembly for a file
core/oat_icon.cpp.s:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_icon.cpp.s
.PHONY : core/oat_icon.cpp.s

core/oat_iconmodule.o: core/oat_iconmodule.cpp.o

.PHONY : core/oat_iconmodule.o

# target to build an object file
core/oat_iconmodule.cpp.o:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_iconmodule.cpp.o
.PHONY : core/oat_iconmodule.cpp.o

core/oat_iconmodule.i: core/oat_iconmodule.cpp.i

.PHONY : core/oat_iconmodule.i

# target to preprocess a source file
core/oat_iconmodule.cpp.i:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_iconmodule.cpp.i
.PHONY : core/oat_iconmodule.cpp.i

core/oat_iconmodule.s: core/oat_iconmodule.cpp.s

.PHONY : core/oat_iconmodule.s

# target to generate assembly for a file
core/oat_iconmodule.cpp.s:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_iconmodule.cpp.s
.PHONY : core/oat_iconmodule.cpp.s

core/oat_image.o: core/oat_image.cpp.o

.PHONY : core/oat_image.o

# target to build an object file
core/oat_image.cpp.o:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_image.cpp.o
.PHONY : core/oat_image.cpp.o

core/oat_image.i: core/oat_image.cpp.i

.PHONY : core/oat_image.i

# target to preprocess a source file
core/oat_image.cpp.i:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_image.cpp.i
.PHONY : core/oat_image.cpp.i

core/oat_image.s: core/oat_image.cpp.s

.PHONY : core/oat_image.s

# target to generate assembly for a file
core/oat_image.cpp.s:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_image.cpp.s
.PHONY : core/oat_image.cpp.s

core/oat_image_directcolor.o: core/oat_image_directcolor.cpp.o

.PHONY : core/oat_image_directcolor.o

# target to build an object file
core/oat_image_directcolor.cpp.o:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_image_directcolor.cpp.o
.PHONY : core/oat_image_directcolor.cpp.o

core/oat_image_directcolor.i: core/oat_image_directcolor.cpp.i

.PHONY : core/oat_image_directcolor.i

# target to preprocess a source file
core/oat_image_directcolor.cpp.i:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_image_directcolor.cpp.i
.PHONY : core/oat_image_directcolor.cpp.i

core/oat_image_directcolor.s: core/oat_image_directcolor.cpp.s

.PHONY : core/oat_image_directcolor.s

# target to generate assembly for a file
core/oat_image_directcolor.cpp.s:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_image_directcolor.cpp.s
.PHONY : core/oat_image_directcolor.cpp.s

core/oat_image_indexcolor.o: core/oat_image_indexcolor.cpp.o

.PHONY : core/oat_image_indexcolor.o

# target to build an object file
core/oat_image_indexcolor.cpp.o:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_image_indexcolor.cpp.o
.PHONY : core/oat_image_indexcolor.cpp.o

core/oat_image_indexcolor.i: core/oat_image_indexcolor.cpp.i

.PHONY : core/oat_image_indexcolor.i

# target to preprocess a source file
core/oat_image_indexcolor.cpp.i:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_image_indexcolor.cpp.i
.PHONY : core/oat_image_indexcolor.cpp.i

core/oat_image_indexcolor.s: core/oat_image_indexcolor.cpp.s

.PHONY : core/oat_image_indexcolor.s

# target to generate assembly for a file
core/oat_image_indexcolor.cpp.s:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_image_indexcolor.cpp.s
.PHONY : core/oat_image_indexcolor.cpp.s

core/oat_master.o: core/oat_master.cpp.o

.PHONY : core/oat_master.o

# target to build an object file
core/oat_master.cpp.o:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_master.cpp.o
.PHONY : core/oat_master.cpp.o

core/oat_master.i: core/oat_master.cpp.i

.PHONY : core/oat_master.i

# target to preprocess a source file
core/oat_master.cpp.i:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_master.cpp.i
.PHONY : core/oat_master.cpp.i

core/oat_master.s: core/oat_master.cpp.s

.PHONY : core/oat_master.s

# target to generate assembly for a file
core/oat_master.cpp.s:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_master.cpp.s
.PHONY : core/oat_master.cpp.s

core/oat_notebook.o: core/oat_notebook.cpp.o

.PHONY : core/oat_notebook.o

# target to build an object file
core/oat_notebook.cpp.o:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_notebook.cpp.o
.PHONY : core/oat_notebook.cpp.o

core/oat_notebook.i: core/oat_notebook.cpp.i

.PHONY : core/oat_notebook.i

# target to preprocess a source file
core/oat_notebook.cpp.i:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_notebook.cpp.i
.PHONY : core/oat_notebook.cpp.i

core/oat_notebook.s: core/oat_notebook.cpp.s

.PHONY : core/oat_notebook.s

# target to generate assembly for a file
core/oat_notebook.cpp.s:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_notebook.cpp.s
.PHONY : core/oat_notebook.cpp.s

core/oat_table.o: core/oat_table.cpp.o

.PHONY : core/oat_table.o

# target to build an object file
core/oat_table.cpp.o:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_table.cpp.o
.PHONY : core/oat_table.cpp.o

core/oat_table.i: core/oat_table.cpp.i

.PHONY : core/oat_table.i

# target to preprocess a source file
core/oat_table.cpp.i:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_table.cpp.i
.PHONY : core/oat_table.cpp.i

core/oat_table.s: core/oat_table.cpp.s

.PHONY : core/oat_table.s

# target to generate assembly for a file
core/oat_table.cpp.s:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_table.cpp.s
.PHONY : core/oat_table.cpp.s

core/oat_text.o: core/oat_text.cpp.o

.PHONY : core/oat_text.o

# target to build an object file
core/oat_text.cpp.o:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_text.cpp.o
.PHONY : core/oat_text.cpp.o

core/oat_text.i: core/oat_text.cpp.i

.PHONY : core/oat_text.i

# target to preprocess a source file
core/oat_text.cpp.i:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_text.cpp.i
.PHONY : core/oat_text.cpp.i

core/oat_text.s: core/oat_text.cpp.s

.PHONY : core/oat_text.s

# target to generate assembly for a file
core/oat_text.cpp.s:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_text.cpp.s
.PHONY : core/oat_text.cpp.s

core/oat_textbox.o: core/oat_textbox.cpp.o

.PHONY : core/oat_textbox.o

# target to build an object file
core/oat_textbox.cpp.o:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_textbox.cpp.o
.PHONY : core/oat_textbox.cpp.o

core/oat_textbox.i: core/oat_textbox.cpp.i

.PHONY : core/oat_textbox.i

# target to preprocess a source file
core/oat_textbox.cpp.i:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_textbox.cpp.i
.PHONY : core/oat_textbox.cpp.i

core/oat_textbox.s: core/oat_textbox.cpp.s

.PHONY : core/oat_textbox.s

# target to generate assembly for a file
core/oat_textbox.cpp.s:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_textbox.cpp.s
.PHONY : core/oat_textbox.cpp.s

core/oat_unicode.o: core/oat_unicode.cpp.o

.PHONY : core/oat_unicode.o

# target to build an object file
core/oat_unicode.cpp.o:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_unicode.cpp.o
.PHONY : core/oat_unicode.cpp.o

core/oat_unicode.i: core/oat_unicode.cpp.i

.PHONY : core/oat_unicode.i

# target to preprocess a source file
core/oat_unicode.cpp.i:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_unicode.cpp.i
.PHONY : core/oat_unicode.cpp.i

core/oat_unicode.s: core/oat_unicode.cpp.s

.PHONY : core/oat_unicode.s

# target to generate assembly for a file
core/oat_unicode.cpp.s:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_unicode.cpp.s
.PHONY : core/oat_unicode.cpp.s

core/oat_widget.o: core/oat_widget.cpp.o

.PHONY : core/oat_widget.o

# target to build an object file
core/oat_widget.cpp.o:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_widget.cpp.o
.PHONY : core/oat_widget.cpp.o

core/oat_widget.i: core/oat_widget.cpp.i

.PHONY : core/oat_widget.i

# target to preprocess a source file
core/oat_widget.cpp.i:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_widget.cpp.i
.PHONY : core/oat_widget.cpp.i

core/oat_widget.s: core/oat_widget.cpp.s

.PHONY : core/oat_widget.s

# target to generate assembly for a file
core/oat_widget.cpp.s:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_widget.cpp.s
.PHONY : core/oat_widget.cpp.s

core/oat_widget_render.o: core/oat_widget_render.cpp.o

.PHONY : core/oat_widget_render.o

# target to build an object file
core/oat_widget_render.cpp.o:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_widget_render.cpp.o
.PHONY : core/oat_widget_render.cpp.o

core/oat_widget_render.i: core/oat_widget_render.cpp.i

.PHONY : core/oat_widget_render.i

# target to preprocess a source file
core/oat_widget_render.cpp.i:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_widget_render.cpp.i
.PHONY : core/oat_widget_render.cpp.i

core/oat_widget_render.s: core/oat_widget_render.cpp.s

.PHONY : core/oat_widget_render.s

# target to generate assembly for a file
core/oat_widget_render.cpp.s:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/core/oat_widget_render.cpp.s
.PHONY : core/oat_widget_render.cpp.s

gramk.o: gramk.cpp.o

.PHONY : gramk.o

# target to build an object file
gramk.cpp.o:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/gramk.cpp.o
.PHONY : gramk.cpp.o

gramk.i: gramk.cpp.i

.PHONY : gramk.i

# target to preprocess a source file
gramk.cpp.i:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/gramk.cpp.i
.PHONY : gramk.cpp.i

gramk.s: gramk.cpp.s

.PHONY : gramk.s

# target to generate assembly for a file
gramk.cpp.s:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/gramk.cpp.s
.PHONY : gramk.cpp.s

gramk/gramk_album.o: gramk/gramk_album.cpp.o

.PHONY : gramk/gramk_album.o

# target to build an object file
gramk/gramk_album.cpp.o:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/gramk/gramk_album.cpp.o
.PHONY : gramk/gramk_album.cpp.o

gramk/gramk_album.i: gramk/gramk_album.cpp.i

.PHONY : gramk/gramk_album.i

# target to preprocess a source file
gramk/gramk_album.cpp.i:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/gramk/gramk_album.cpp.i
.PHONY : gramk/gramk_album.cpp.i

gramk/gramk_album.s: gramk/gramk_album.cpp.s

.PHONY : gramk/gramk_album.s

# target to generate assembly for a file
gramk/gramk_album.cpp.s:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/gramk/gramk_album.cpp.s
.PHONY : gramk/gramk_album.cpp.s

gramk/gramk_album__file.o: gramk/gramk_album__file.cpp.o

.PHONY : gramk/gramk_album__file.o

# target to build an object file
gramk/gramk_album__file.cpp.o:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/gramk/gramk_album__file.cpp.o
.PHONY : gramk/gramk_album__file.cpp.o

gramk/gramk_album__file.i: gramk/gramk_album__file.cpp.i

.PHONY : gramk/gramk_album__file.i

# target to preprocess a source file
gramk/gramk_album__file.cpp.i:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/gramk/gramk_album__file.cpp.i
.PHONY : gramk/gramk_album__file.cpp.i

gramk/gramk_album__file.s: gramk/gramk_album__file.cpp.s

.PHONY : gramk/gramk_album__file.s

# target to generate assembly for a file
gramk/gramk_album__file.cpp.s:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/gramk/gramk_album__file.cpp.s
.PHONY : gramk/gramk_album__file.cpp.s

gramk/gramk_anibox.o: gramk/gramk_anibox.cpp.o

.PHONY : gramk/gramk_anibox.o

# target to build an object file
gramk/gramk_anibox.cpp.o:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/gramk/gramk_anibox.cpp.o
.PHONY : gramk/gramk_anibox.cpp.o

gramk/gramk_anibox.i: gramk/gramk_anibox.cpp.i

.PHONY : gramk/gramk_anibox.i

# target to preprocess a source file
gramk/gramk_anibox.cpp.i:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/gramk/gramk_anibox.cpp.i
.PHONY : gramk/gramk_anibox.cpp.i

gramk/gramk_anibox.s: gramk/gramk_anibox.cpp.s

.PHONY : gramk/gramk_anibox.s

# target to generate assembly for a file
gramk/gramk_anibox.cpp.s:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/gramk/gramk_anibox.cpp.s
.PHONY : gramk/gramk_anibox.cpp.s

gramk/gramk_card.o: gramk/gramk_card.cpp.o

.PHONY : gramk/gramk_card.o

# target to build an object file
gramk/gramk_card.cpp.o:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/gramk/gramk_card.cpp.o
.PHONY : gramk/gramk_card.cpp.o

gramk/gramk_card.i: gramk/gramk_card.cpp.i

.PHONY : gramk/gramk_card.i

# target to preprocess a source file
gramk/gramk_card.cpp.i:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/gramk/gramk_card.cpp.i
.PHONY : gramk/gramk_card.cpp.i

gramk/gramk_card.s: gramk/gramk_card.cpp.s

.PHONY : gramk/gramk_card.s

# target to generate assembly for a file
gramk/gramk_card.cpp.s:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/gramk/gramk_card.cpp.s
.PHONY : gramk/gramk_card.cpp.s

gramk/gramk_clip.o: gramk/gramk_clip.cpp.o

.PHONY : gramk/gramk_clip.o

# target to build an object file
gramk/gramk_clip.cpp.o:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/gramk/gramk_clip.cpp.o
.PHONY : gramk/gramk_clip.cpp.o

gramk/gramk_clip.i: gramk/gramk_clip.cpp.i

.PHONY : gramk/gramk_clip.i

# target to preprocess a source file
gramk/gramk_clip.cpp.i:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/gramk/gramk_clip.cpp.i
.PHONY : gramk/gramk_clip.cpp.i

gramk/gramk_clip.s: gramk/gramk_clip.cpp.s

.PHONY : gramk/gramk_clip.s

# target to generate assembly for a file
gramk/gramk_clip.cpp.s:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/gramk/gramk_clip.cpp.s
.PHONY : gramk/gramk_clip.cpp.s

gramk/gramk_drawing.o: gramk/gramk_drawing.cpp.o

.PHONY : gramk/gramk_drawing.o

# target to build an object file
gramk/gramk_drawing.cpp.o:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/gramk/gramk_drawing.cpp.o
.PHONY : gramk/gramk_drawing.cpp.o

gramk/gramk_drawing.i: gramk/gramk_drawing.cpp.i

.PHONY : gramk/gramk_drawing.i

# target to preprocess a source file
gramk/gramk_drawing.cpp.i:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/gramk/gramk_drawing.cpp.i
.PHONY : gramk/gramk_drawing.cpp.i

gramk/gramk_drawing.s: gramk/gramk_drawing.cpp.s

.PHONY : gramk/gramk_drawing.s

# target to generate assembly for a file
gramk/gramk_drawing.cpp.s:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/gramk/gramk_drawing.cpp.s
.PHONY : gramk/gramk_drawing.cpp.s

gramk/gramk_painter.o: gramk/gramk_painter.cpp.o

.PHONY : gramk/gramk_painter.o

# target to build an object file
gramk/gramk_painter.cpp.o:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/gramk/gramk_painter.cpp.o
.PHONY : gramk/gramk_painter.cpp.o

gramk/gramk_painter.i: gramk/gramk_painter.cpp.i

.PHONY : gramk/gramk_painter.i

# target to preprocess a source file
gramk/gramk_painter.cpp.i:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/gramk/gramk_painter.cpp.i
.PHONY : gramk/gramk_painter.cpp.i

gramk/gramk_painter.s: gramk/gramk_painter.cpp.s

.PHONY : gramk/gramk_painter.s

# target to generate assembly for a file
gramk/gramk_painter.cpp.s:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/gramk/gramk_painter.cpp.s
.PHONY : gramk/gramk_painter.cpp.s

gramk/gramk_painter__create_mode_widget.o: gramk/gramk_painter__create_mode_widget.cpp.o

.PHONY : gramk/gramk_painter__create_mode_widget.o

# target to build an object file
gramk/gramk_painter__create_mode_widget.cpp.o:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/gramk/gramk_painter__create_mode_widget.cpp.o
.PHONY : gramk/gramk_painter__create_mode_widget.cpp.o

gramk/gramk_painter__create_mode_widget.i: gramk/gramk_painter__create_mode_widget.cpp.i

.PHONY : gramk/gramk_painter__create_mode_widget.i

# target to preprocess a source file
gramk/gramk_painter__create_mode_widget.cpp.i:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/gramk/gramk_painter__create_mode_widget.cpp.i
.PHONY : gramk/gramk_painter__create_mode_widget.cpp.i

gramk/gramk_painter__create_mode_widget.s: gramk/gramk_painter__create_mode_widget.cpp.s

.PHONY : gramk/gramk_painter__create_mode_widget.s

# target to generate assembly for a file
gramk/gramk_painter__create_mode_widget.cpp.s:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/gramk/gramk_painter__create_mode_widget.cpp.s
.PHONY : gramk/gramk_painter__create_mode_widget.cpp.s

gramk/gramk_painter__create_oper_widget.o: gramk/gramk_painter__create_oper_widget.cpp.o

.PHONY : gramk/gramk_painter__create_oper_widget.o

# target to build an object file
gramk/gramk_painter__create_oper_widget.cpp.o:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/gramk/gramk_painter__create_oper_widget.cpp.o
.PHONY : gramk/gramk_painter__create_oper_widget.cpp.o

gramk/gramk_painter__create_oper_widget.i: gramk/gramk_painter__create_oper_widget.cpp.i

.PHONY : gramk/gramk_painter__create_oper_widget.i

# target to preprocess a source file
gramk/gramk_painter__create_oper_widget.cpp.i:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/gramk/gramk_painter__create_oper_widget.cpp.i
.PHONY : gramk/gramk_painter__create_oper_widget.cpp.i

gramk/gramk_painter__create_oper_widget.s: gramk/gramk_painter__create_oper_widget.cpp.s

.PHONY : gramk/gramk_painter__create_oper_widget.s

# target to generate assembly for a file
gramk/gramk_painter__create_oper_widget.cpp.s:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/gramk/gramk_painter__create_oper_widget.cpp.s
.PHONY : gramk/gramk_painter__create_oper_widget.cpp.s

gramk/gramk_painter__create_palette_widget.o: gramk/gramk_painter__create_palette_widget.cpp.o

.PHONY : gramk/gramk_painter__create_palette_widget.o

# target to build an object file
gramk/gramk_painter__create_palette_widget.cpp.o:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/gramk/gramk_painter__create_palette_widget.cpp.o
.PHONY : gramk/gramk_painter__create_palette_widget.cpp.o

gramk/gramk_painter__create_palette_widget.i: gramk/gramk_painter__create_palette_widget.cpp.i

.PHONY : gramk/gramk_painter__create_palette_widget.i

# target to preprocess a source file
gramk/gramk_painter__create_palette_widget.cpp.i:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/gramk/gramk_painter__create_palette_widget.cpp.i
.PHONY : gramk/gramk_painter__create_palette_widget.cpp.i

gramk/gramk_painter__create_palette_widget.s: gramk/gramk_painter__create_palette_widget.cpp.s

.PHONY : gramk/gramk_painter__create_palette_widget.s

# target to generate assembly for a file
gramk/gramk_painter__create_palette_widget.cpp.s:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/gramk/gramk_painter__create_palette_widget.cpp.s
.PHONY : gramk/gramk_painter__create_palette_widget.cpp.s

gramk/gramk_painter__move_corner.o: gramk/gramk_painter__move_corner.cpp.o

.PHONY : gramk/gramk_painter__move_corner.o

# target to build an object file
gramk/gramk_painter__move_corner.cpp.o:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/gramk/gramk_painter__move_corner.cpp.o
.PHONY : gramk/gramk_painter__move_corner.cpp.o

gramk/gramk_painter__move_corner.i: gramk/gramk_painter__move_corner.cpp.i

.PHONY : gramk/gramk_painter__move_corner.i

# target to preprocess a source file
gramk/gramk_painter__move_corner.cpp.i:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/gramk/gramk_painter__move_corner.cpp.i
.PHONY : gramk/gramk_painter__move_corner.cpp.i

gramk/gramk_painter__move_corner.s: gramk/gramk_painter__move_corner.cpp.s

.PHONY : gramk/gramk_painter__move_corner.s

# target to generate assembly for a file
gramk/gramk_painter__move_corner.cpp.s:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/gramk/gramk_painter__move_corner.cpp.s
.PHONY : gramk/gramk_painter__move_corner.cpp.s

gramk/gramk_supercard.o: gramk/gramk_supercard.cpp.o

.PHONY : gramk/gramk_supercard.o

# target to build an object file
gramk/gramk_supercard.cpp.o:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/gramk/gramk_supercard.cpp.o
.PHONY : gramk/gramk_supercard.cpp.o

gramk/gramk_supercard.i: gramk/gramk_supercard.cpp.i

.PHONY : gramk/gramk_supercard.i

# target to preprocess a source file
gramk/gramk_supercard.cpp.i:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/gramk/gramk_supercard.cpp.i
.PHONY : gramk/gramk_supercard.cpp.i

gramk/gramk_supercard.s: gramk/gramk_supercard.cpp.s

.PHONY : gramk/gramk_supercard.s

# target to generate assembly for a file
gramk/gramk_supercard.cpp.s:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/gramk/gramk_supercard.cpp.s
.PHONY : gramk/gramk_supercard.cpp.s

gramk/gramk_supercard__fill_area.o: gramk/gramk_supercard__fill_area.cpp.o

.PHONY : gramk/gramk_supercard__fill_area.o

# target to build an object file
gramk/gramk_supercard__fill_area.cpp.o:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/gramk/gramk_supercard__fill_area.cpp.o
.PHONY : gramk/gramk_supercard__fill_area.cpp.o

gramk/gramk_supercard__fill_area.i: gramk/gramk_supercard__fill_area.cpp.i

.PHONY : gramk/gramk_supercard__fill_area.i

# target to preprocess a source file
gramk/gramk_supercard__fill_area.cpp.i:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/gramk/gramk_supercard__fill_area.cpp.i
.PHONY : gramk/gramk_supercard__fill_area.cpp.i

gramk/gramk_supercard__fill_area.s: gramk/gramk_supercard__fill_area.cpp.s

.PHONY : gramk/gramk_supercard__fill_area.s

# target to generate assembly for a file
gramk/gramk_supercard__fill_area.cpp.s:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/gramk/gramk_supercard__fill_area.cpp.s
.PHONY : gramk/gramk_supercard__fill_area.cpp.s

gramk/gramk_supercard__shift.o: gramk/gramk_supercard__shift.cpp.o

.PHONY : gramk/gramk_supercard__shift.o

# target to build an object file
gramk/gramk_supercard__shift.cpp.o:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/gramk/gramk_supercard__shift.cpp.o
.PHONY : gramk/gramk_supercard__shift.cpp.o

gramk/gramk_supercard__shift.i: gramk/gramk_supercard__shift.cpp.i

.PHONY : gramk/gramk_supercard__shift.i

# target to preprocess a source file
gramk/gramk_supercard__shift.cpp.i:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/gramk/gramk_supercard__shift.cpp.i
.PHONY : gramk/gramk_supercard__shift.cpp.i

gramk/gramk_supercard__shift.s: gramk/gramk_supercard__shift.cpp.s

.PHONY : gramk/gramk_supercard__shift.s

# target to generate assembly for a file
gramk/gramk_supercard__shift.cpp.s:
	$(MAKE) -f CMakeFiles/Gramk.dir/build.make CMakeFiles/Gramk.dir/gramk/gramk_supercard__shift.cpp.s
.PHONY : gramk/gramk_supercard__shift.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Gramk"
	@echo "... core/oat.o"
	@echo "... core/oat.i"
	@echo "... core/oat.s"
	@echo "... core/oat_box.o"
	@echo "... core/oat_box.i"
	@echo "... core/oat_box.s"
	@echo "... core/oat_button.o"
	@echo "... core/oat_button.i"
	@echo "... core/oat_button.s"
	@echo "... core/oat_buttonmodule.o"
	@echo "... core/oat_buttonmodule.i"
	@echo "... core/oat_buttonmodule.s"
	@echo "... core/oat_checkform.o"
	@echo "... core/oat_checkform.i"
	@echo "... core/oat_checkform.s"
	@echo "... core/oat_color.o"
	@echo "... core/oat_color.i"
	@echo "... core/oat_color.s"
	@echo "... core/oat_container.o"
	@echo "... core/oat_container.i"
	@echo "... core/oat_container.s"
	@echo "... core/oat_cross.o"
	@echo "... core/oat_cross.i"
	@echo "... core/oat_cross.s"
	@echo "... core/oat_dial.o"
	@echo "... core/oat_dial.i"
	@echo "... core/oat_dial.s"
	@echo "... core/oat_font.o"
	@echo "... core/oat_font.i"
	@echo "... core/oat_font.s"
	@echo "... core/oat_icon.o"
	@echo "... core/oat_icon.i"
	@echo "... core/oat_icon.s"
	@echo "... core/oat_iconmodule.o"
	@echo "... core/oat_iconmodule.i"
	@echo "... core/oat_iconmodule.s"
	@echo "... core/oat_image.o"
	@echo "... core/oat_image.i"
	@echo "... core/oat_image.s"
	@echo "... core/oat_image_directcolor.o"
	@echo "... core/oat_image_directcolor.i"
	@echo "... core/oat_image_directcolor.s"
	@echo "... core/oat_image_indexcolor.o"
	@echo "... core/oat_image_indexcolor.i"
	@echo "... core/oat_image_indexcolor.s"
	@echo "... core/oat_master.o"
	@echo "... core/oat_master.i"
	@echo "... core/oat_master.s"
	@echo "... core/oat_notebook.o"
	@echo "... core/oat_notebook.i"
	@echo "... core/oat_notebook.s"
	@echo "... core/oat_table.o"
	@echo "... core/oat_table.i"
	@echo "... core/oat_table.s"
	@echo "... core/oat_text.o"
	@echo "... core/oat_text.i"
	@echo "... core/oat_text.s"
	@echo "... core/oat_textbox.o"
	@echo "... core/oat_textbox.i"
	@echo "... core/oat_textbox.s"
	@echo "... core/oat_unicode.o"
	@echo "... core/oat_unicode.i"
	@echo "... core/oat_unicode.s"
	@echo "... core/oat_widget.o"
	@echo "... core/oat_widget.i"
	@echo "... core/oat_widget.s"
	@echo "... core/oat_widget_render.o"
	@echo "... core/oat_widget_render.i"
	@echo "... core/oat_widget_render.s"
	@echo "... gramk.o"
	@echo "... gramk.i"
	@echo "... gramk.s"
	@echo "... gramk/gramk_album.o"
	@echo "... gramk/gramk_album.i"
	@echo "... gramk/gramk_album.s"
	@echo "... gramk/gramk_album__file.o"
	@echo "... gramk/gramk_album__file.i"
	@echo "... gramk/gramk_album__file.s"
	@echo "... gramk/gramk_anibox.o"
	@echo "... gramk/gramk_anibox.i"
	@echo "... gramk/gramk_anibox.s"
	@echo "... gramk/gramk_card.o"
	@echo "... gramk/gramk_card.i"
	@echo "... gramk/gramk_card.s"
	@echo "... gramk/gramk_clip.o"
	@echo "... gramk/gramk_clip.i"
	@echo "... gramk/gramk_clip.s"
	@echo "... gramk/gramk_drawing.o"
	@echo "... gramk/gramk_drawing.i"
	@echo "... gramk/gramk_drawing.s"
	@echo "... gramk/gramk_painter.o"
	@echo "... gramk/gramk_painter.i"
	@echo "... gramk/gramk_painter.s"
	@echo "... gramk/gramk_painter__create_mode_widget.o"
	@echo "... gramk/gramk_painter__create_mode_widget.i"
	@echo "... gramk/gramk_painter__create_mode_widget.s"
	@echo "... gramk/gramk_painter__create_oper_widget.o"
	@echo "... gramk/gramk_painter__create_oper_widget.i"
	@echo "... gramk/gramk_painter__create_oper_widget.s"
	@echo "... gramk/gramk_painter__create_palette_widget.o"
	@echo "... gramk/gramk_painter__create_palette_widget.i"
	@echo "... gramk/gramk_painter__create_palette_widget.s"
	@echo "... gramk/gramk_painter__move_corner.o"
	@echo "... gramk/gramk_painter__move_corner.i"
	@echo "... gramk/gramk_painter__move_corner.s"
	@echo "... gramk/gramk_supercard.o"
	@echo "... gramk/gramk_supercard.i"
	@echo "... gramk/gramk_supercard.s"
	@echo "... gramk/gramk_supercard__fill_area.o"
	@echo "... gramk/gramk_supercard__fill_area.i"
	@echo "... gramk/gramk_supercard__fill_area.s"
	@echo "... gramk/gramk_supercard__shift.o"
	@echo "... gramk/gramk_supercard__shift.i"
	@echo "... gramk/gramk_supercard__shift.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

